<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>INDEX</title>
    <link rel="stylesheet" href="EstiloMP.css">
</head>
<body>
<header id="header">
        <img src="LogoSGC.png" ver ="left" height="117" width="150"/>
		<h2>Drogueria punto express</h2>
			<table id="superior"><tr>
			<td id="superior1"><a href="u_login.php">Login</a></td>
            <td id="superior1"><a href="INDEX.php">Inicio</a></td>
			<td id="superior1"><a href="indexres1407.php">Resolución 1407</a></td>
			<td id="superior1"><a href="indexsisinf.php">Información del sistema</a></td>
            </tr></table>
</header>
<div id="contenido">
<main id="contenidos">

<h1>Bienvenido al sistema de gestion de calidad</h1>

<p>Para nuestra compañia es muy importante cumplir con las normas del gobierno y garantiar su seguridad y la de cada persona que use
   nuestros servicios y productos; al igual que el personal que labora en nuestra compañia, por eso lo invitamos a navegar por
   nuestra pagina web para conocer el programa de gestion de calidad.
</p>

<form id="" action="qrpersonainf.html" method="post">
<p>Puede dejarnos sus comentarios y/o sugerencias en nuestra encuesta de safisfaccion de cliente.<br />
<button type="submit">Encuesta Satisfacción al cliente</button>
</p>
<p>Para quejas y reclamos puede dearlos en el siguiente formulario y nuestro personal lo contactara para dar pronta respuesta.<br />
<button type="submit">Quejas y/o Reclamos</button>
</p>
</main>
</div>
<footer id="footer">
      <center>
        <table id="inferior"><tr>
			<td id="inferior1">Direcci&oacute;n: Cra 101 No. 25 - 45</td>
			<td id="inferior1">Tel&eacute;fono: 601 745 7898</td>
			<td id="inferior1">E-mail:<a href="mailto:drogueriapuntoexpress@gmail.com">drogueriapuntoexpress@gmail.com</a></td>
		</tr></table>
       </center>
</footer>
</body>
</html>